/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cmr;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableModel;
    import javax.swing.*;
import java.util.concurrent.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;


/**
 *
 * @author SMAT
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton4.setText("ALL RECORDES");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "District", "Station", "NIC Number", "Name", "Gender", "Father Name	", "Crime Details"
            }
        ));
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private static Object lock = new Object();
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //        This example creates a new thread, t1, and runs the run() method inside
        //                it. Inside the run() method, the MySQL driver is loaded, a connection
        //                        to the database is established, a statement is created, and a
        //                                query is executed. The query results are processed,
        //                                and the connection is closed.
        //Before executing the database connection, statement and
        //        query operations, the code synchronizes on the lock object,
        //                this ensures that multiple threads can't access the same
        //                        resources simultaneously and cause data inconsistencies.
        //It is important to note that, when working with databases and
        //        multithreading, you should pay attention to synchronization
        //                and concurrency issues. It is recommended that you use a
        //                        connection pooling mechanism such as c3p0, HikariCP
        //                                , or DBCP to improve performance and manage
        //                                        connections more effectively.
        //Additionally, if you are planning to use multiple threads to perform
        //        concurrent database operations, you should consider using a
        //                database management system that supports transactions,
        //                and you should use the JDBC connection.setAutoCommit(false
            //                ) method to disable auto-commit and use connection.commit()
        //                        and connection.rollback() methods to control the transaction.
        Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
                // Synchronize on the lock object
                synchronized(lock) {
                    try{
                        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/cmr", "root", "");//Establishing connection

                        //  Create the insert statement
                        Statement statement =connection.createStatement();
                        String sql="select * from recordes";
                        ResultSet rs=statement.executeQuery(sql);
                        while(rs.next()){
                            String district=rs.getString("district");
                            String station=rs.getString("station");
                            String nic =rs.getString("nic");
                            String name=rs.getString("name");
                            String gender=rs.getString("gender");
                            String fathername=rs.getString("fathername");
                                     String crime=rs.getString("crime");
                            String tbData[] ={district,station,nic,name,gender,fathername,crime};
                            //DefaultTableModel tblModel= (DefaultTableModel) jTable1.getModel();
                            DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();

                            tblModel.addRow(tbData);

                        }
                        connection.close();

                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null,"Connection Error");

                        e.printStackTrace();
                    }
                }
            }
        });
        t1.start();
        jTable1.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1ComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         dispose();
        Search ul=new Search();
                ul.setLocationRelativeTo(null);
        ul.setVisible(true);
//         Thread t1 = new Thread(new Runnable() {
//            @Override
//            public void run() {
//                // Synchronize on the lock object
//                synchronized(lock) {
//   try{
//                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/cmr", "root", "");//Establishing connection
//
////  Create the insert statement
//            String sql="select * from recordes where nic = ?";
//                        Statement statement =connection.prepareStatement(sql);
//                        statement.setString(1,txtsearch.getText());
//            ResultSet rs=statement.executeQuery(sql);
//         while(rs.next()){
//         String district=rs.getString("district");
//         String station=rs.getString("station");
//         String nic =rs.getString("nic");
//         String name=rs.getString("name");
//         String gender=rs.getString("gender");
//         String fathername=rs.getString("fathername");
////         String station=rs.getString("station");
//String tbData[] ={district,station,nic,name,gender,fathername};
////DefaultTableModel tblModel= (DefaultTableModel) jTable1.getModel();
// DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel(); 
//
//tblModel.addRow(tbData);
//         
//                 
//         }
//            connection.close();
//        
//        }
//        catch(Exception e){
//           JOptionPane.showMessageDialog(null,"Connection Error");
//        
//                        e.printStackTrace();
//                    }
//                }
//            }
//        });
//        t1.start();       
//        jTable1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
